"""
ℚ(ζ_7) — order-6 cyclotomic test.

Galois group (Z/7)* ≅ Z/6, generated by 3 (since 3 is a primitive root mod 7).
Order-6 character chi: chi(3) = ω = e^{2πi/6} = (1+i√3)/2

The 6 character values are the 6th roots of unity:
  chi(1) = 1     = +1
  chi(3) = ω    = (1+i√3)/2
  chi(2) = ω²   = (-1+i√3)/2
  chi(6) = ω³   = -1
  chi(4) = ω⁴   = (-1-i√3)/2
  chi(5) = ω⁵   = (1-i√3)/2

Test: do these six values appear at SIX distinct, well-separated positions
in the (F_cos, F_sin) plane after framework recovery?
"""
import math, os, time
import numpy as np
from mpmath import mp, mpf, mpc, zeta as mp_zeta, gamma as mp_gamma, pi as mp_pi, exp as mp_exp
mp.dps = 20

OUTDIR = "/home/claude/cyclotomic_7"
os.makedirs(OUTDIR, exist_ok=True)

# Build chi of order 6 mod 7
# 3 is generator of (Z/7)*: 3^1=3, 3^2=2, 3^3=6, 3^4=4, 3^5=5, 3^6=1
omega = mp_exp(2 * mp_pi * mpc(0, 1) / 6)
print(f"ω = e^(2πi/6) = {omega}")
print(f"|ω| = {abs(omega)}")

# Build character table
chi_vals = {}
chi_vals[0] = mpc(0)
# Map n → power_of_3 mod 6
disc_log = {}  # n -> k where 3^k ≡ n mod 7
power = 1
for k in range(6):
    disc_log[power] = k
    power = (power * 3) % 7
print(f"Discrete log table (base 3 mod 7): {disc_log}")

for n in range(1, 7):
    if n in disc_log:
        chi_vals[n] = omega ** disc_log[n]
    else:
        chi_vals[n] = mpc(0)

# Print character
print(f"\nCharacter mod 7 (order 6):")
for n in range(7):
    v = chi_vals[n]
    if abs(v) > 1e-10:
        re = float(v.real); im = float(v.imag)
        print(f"  chi({n}) = {re:+.4f} + {im:+.4f}i  (|chi|={float(abs(v)):.4f})")
    else:
        print(f"  chi({n}) = 0")

# Verify oddness
print(f"\nchi(-1) = chi(6) = {chi_vals[6]} (should be -1 for odd character)")

# Gauss sum
def gauss_sum():
    total = mpc(0)
    for a in range(1, 7):
        total += chi_vals[a] * mp_exp(2 * mp_pi * mpc(0, 1) * a / 7)
    return total

tau = gauss_sum()
print(f"\nGauss sum τ(χ) = {tau}")
print(f"|τ|² = {abs(tau)**2} (should equal q=7)")

# Root number ε(χ) = τ(χ) / (i√q) for odd character
epsilon = tau / (mpc(0, 1) * mpf(7)**mpf('0.5'))
print(f"ε(χ) = {epsilon}")
print(f"|ε|² = {abs(epsilon)**2}")
arg_eps = math.atan2(float(epsilon.imag), float(epsilon.real))
print(f"arg(ε) = {arg_eps:.5f} rad ({math.degrees(arg_eps):.2f}°)")
phase_rot = arg_eps / 2

# L-function via Hurwitz zeta
def L_chi(s):
    total = mpc(0)
    for a in range(1, 7):
        if abs(chi_vals[a]) > 1e-10:
            total += chi_vals[a] * mp_zeta(s, mpf(a)/7)
    return mpf(7)**(-s) * total

def Lambda_chi(t):
    s = mpc(0.5, t)
    factor1 = (mpf(7) / mp_pi) ** (s/2)
    factor2 = mp_gamma((s + 1) / 2)
    return factor1 * factor2 * L_chi(s)

# Z function — should be real
phase_factor = mp_exp(mpc(0, -phase_rot))
def Z(t):
    lam = Lambda_chi(t)
    rotated = phase_factor * lam
    return float(rotated.real)

# Verify Z is real
print(f"\nVerify Z(t) is real (imag part should be ~0):")
for t_test in [0.5, 1.0, 5.0, 10.0, 20.0, 50.0]:
    lam = Lambda_chi(t_test)
    rotated = phase_factor * lam
    print(f"  t={t_test:5.1f}: Z = {float(rotated.real):+.5f}, imag = {float(rotated.imag):+.2e}")

# Time check
t0 = time.time()
val = Z(10.0)
elapsed = time.time() - t0
print(f"\nOne Z eval: {elapsed:.3f}s, rate {1/elapsed:.0f}/s")

# Find zeros
T_MAX = 100.0
DT = 0.1
t_vals = np.arange(0.01, T_MAX, DT)
print(f"Scanning {len(t_vals)} points for Z(t) zeros...")

Z_vals = np.zeros(len(t_vals))
t0 = time.time()
for i, t in enumerate(t_vals):
    if i % 200 == 0 and i > 0:
        e = time.time() - t0
        print(f"  {i}/{len(t_vals)}  rate={i/e:.0f}/s")
    Z_vals[i] = Z(float(t))
print(f"Scan done in {time.time()-t0:.1f}s")

sign_changes = np.where(np.diff(np.sign(Z_vals)) != 0)[0]
print(f"Sign changes: {len(sign_changes)}")

def bisect(t_lo, t_hi):
    f_lo = Z(t_lo); f_hi = Z(t_hi)
    if f_lo * f_hi >= 0: return None
    for _ in range(40):
        t_mid = (t_lo + t_hi) / 2
        f_mid = Z(t_mid)
        if abs(f_mid) < 1e-8 or (t_hi-t_lo) < 1e-8: return t_mid
        if f_lo * f_mid < 0: t_hi = t_mid; f_hi = f_mid
        else: t_lo = t_mid; f_lo = f_mid
    return (t_lo + t_hi) / 2

zeros = []
for idx in sign_changes:
    z = bisect(t_vals[idx], t_vals[idx+1])
    if z is not None: zeros.append(z)
zeros = np.array(sorted(zeros))
diffs = np.diff(zeros)
zeros = zeros[np.concatenate([[True], diffs > 0.1])]
print(f"\nZeros: {len(zeros)}, range [{zeros[0]:.2f}, {zeros[-1]:.2f}]")
print(f"First 10: {zeros[:10]}")

# Density check
predicted = (zeros[-1]/(2*math.pi)) * math.log(7*zeros[-1]/(2*math.pi)) - zeros[-1]/(2*math.pi)
print(f"Predicted count at T={zeros[-1]:.0f}: {predicted:.1f}")

np.savetxt(f"{OUTDIR}/zeros_chi_7_order6.txt", zeros, fmt='%.10f')
