#!/usr/bin/env python3

# Co-governed and enforced under the Sovereign Integrity Protocol License (SIP License v1.1):
# https://github.com/tensorrent/ACS-Framework/blob/main/LICENSE
"""
TASK 1: TM1 PMNS REDO FROM PALATINI YUKAWA STRUCTURE
======================================================
Question: does the Palatini bracket structure naturally pick TM1
(tri-maximal 1) over TBM (tri-bimaximal)?

TBM = Harrison-Perkins-Scott 2002. Predicts θ_13 = 0. Ruled out 2012.
TM1 = first column fixed at (2/√6, -1/√6, -1/√6). θ_13 ≠ 0 allowed.
TM2 = second column fixed at (1/√3, 1/√3, 1/√3). Different preds.

The flavor symmetry perspective:
  TBM    respects full S_4 symmetry
  TM1    respects residual Z_2 (from S_4 → Z_2 in charged-lepton sector)
  TM2    respects residual Z_2 (different Z_2)

The Palatini perspective (this task):
  The bracket [T_BL, ·] has 3-eigenvalue structure (Theorem C).
  The neutrino mass matrix should inherit this.
  Which of TBM/TM1/TM2 is naturally selected by this structure?
"""
import numpy as np
from sympy import Matrix, symbols, sqrt, Rational, simplify, cos, sin
from sympy import I as sym_I, exp, zeros, eye, solve, expand, conjugate
from sympy import atan2, asin, pi, N, nsimplify

print("=" * 72)
print("TASK 1.1: THREE ANSÄTZE AND THEIR BRACKET-ALGEBRA STRUCTURES")
print("=" * 72)

# Build the three mixing matrices symbolically
TBM = Matrix([
    [sqrt(Rational(2,3)),   sqrt(Rational(1,3)),    0],
    [-sqrt(Rational(1,6)),  sqrt(Rational(1,3)),    sqrt(Rational(1,2))],
    [sqrt(Rational(1,6)),   -sqrt(Rational(1,3)),   sqrt(Rational(1,2))]
])

# TM1: first column fixed, other two rotate by θ
theta = symbols('theta', real=True)
TM1 = Matrix([
    [sqrt(Rational(2,3)),                                    cos(theta)/sqrt(3),         sin(theta)/sqrt(3)],
    [-sqrt(Rational(1,6)),   cos(theta)/sqrt(3) + sin(theta)/sqrt(2),  sin(theta)/sqrt(3) - cos(theta)/sqrt(2)],
    [sqrt(Rational(1,6)),    cos(theta)/sqrt(3) - sin(theta)/sqrt(2),  sin(theta)/sqrt(3) + cos(theta)/sqrt(2)]
])

# TM2: second column fixed
TM2 = Matrix([
    [cos(theta)*sqrt(Rational(2,3)),    sqrt(Rational(1,3)),    sin(theta)*sqrt(Rational(2,3))],
    [-cos(theta)/sqrt(6) - sin(theta)/sqrt(2),   sqrt(Rational(1,3)),    -sin(theta)/sqrt(6) + cos(theta)/sqrt(2)],
    [-cos(theta)/sqrt(6) + sin(theta)/sqrt(2),   sqrt(Rational(1,3)),    -sin(theta)/sqrt(6) - cos(theta)/sqrt(2)]
])

print("""
TBM: all three columns fixed (S_4 symmetric).
  Column 1 = (√(2/3), -√(1/6), √(1/6))
  Column 2 = (√(1/3), √(1/3), -√(1/3))
  Column 3 = (0, √(1/2), √(1/2))

TM1: first column fixed at TBM value.
  Columns 2 and 3 rotate by free angle θ.
  Preserves Z_2 symmetry generated by specific element of S_4.

TM2: second column fixed at TBM value.
  Columns 1 and 3 rotate by free angle θ.
  Preserves a different Z_2.
""")

# Verify each is orthogonal
print("Orthogonality checks:")
print(f"  TBM · TBM^T = I: {simplify(TBM * TBM.T) == eye(3)}")
print(f"  TM1 · TM1^T = I (symbolic θ): {simplify(TM1 * TM1.T) == eye(3)}")
print(f"  TM2 · TM2^T = I (symbolic θ): {simplify(TM2 * TM2.T) == eye(3)}")

print("\n" + "=" * 72)
print("TASK 1.2: WHICH ANSATZ IS NATURAL UNDER PALATINI?")
print("=" * 72)

print(r"""
The Palatini bracket [T_BL, ·] on sl(4,R) has the following structure
(Theorem C):
  - eigenvalue 0   with eigenspace dim 9
  - eigenvalue +4/3 with eigenspace dim 3
  - eigenvalue -4/3 with eigenspace dim 3

The lepton sector decomposes under T_BL as follows:
  - Quarks sit at SU(4) indices {0,1,2} with eigenvalue +1/3
  - Leptons sit at SU(4) index {3} with eigenvalue -1
  - Quark-lepton mixing sits at index pairs (i, 3) for i=0,1,2
    with ad_T_BL eigenvalue (1/3 - (-1)) = 4/3

KEY OBSERVATION:
  The three generations (by Theorem C) each couple to the "lepton"
  direction (index 3) via an element of the +4/3 eigenspace.
  
  The three elements of the +4/3 eigenspace are:
     {A_{03} + S_{03}, A_{13} + S_{13}, A_{23} + S_{23}}
  
  (where A is antisymmetric and S is symmetric off-diagonal)
  
  Each of these mixes ONE specific quark-like index with the lepton.

THIS GIVES A 3-DIMENSIONAL MIXING STRUCTURE. The natural basis of
this mixing is labeled by the quark index i = 0, 1, 2.

QUESTION: Does this give TBM, TM1, or TM2?
""")

# Compute the 3×3 structure of the mixing
# The neutrino mass matrix inherits ad_T_BL's eigenspace structure
# In the basis where T_BL is diagonal, the mass matrix has block form

# Let me build the explicit bracket-derived mass matrix
# The see-saw formula: m_nu = m_D * M_R^{-1} * m_D^T
# Where m_D has structure inherited from the bi-doublet Yukawa
# And M_R has structure inherited from the Delta_R Yukawa

# At the level of the Palatini bracket, the structure is:
# m_D_ij ∝ (bracket-induced coupling of Φ to fermion bilinear i-j)
# These couplings come in three types matching the three ad_T_BL
# eigenspaces

# Simplest natural ansatz: m_D diagonal in "bracket-eigenbasis"
# with eigenvalues proportional to the ad_T_BL eigenvalues

# Let's build this and see what mixing pattern it gives

# Yukawa structure from Palatini bracket:
# Y_D = y_0 · 1 + y_+ · P_+ + y_- · P_-
# where P_± are projectors onto the ±4/3 eigenspaces (restricted to generation space)

# In generation space (3×3), the three eigenspaces of ad_T_BL give three
# 1-dim subspaces. The projectors on these are rank-1 matrices.

# Concretely (following the structure of ad_T_BL on the three (i,3) mixing
# elements), the natural basis vectors in generation space are:
# e_1 = (1,0,0), e_2 = (0,1,0), e_3 = (0,0,1) aligned with SU(4) indices

# The "democratic" mixing comes from the fact that each generation
# couples equally (by T_BL symmetry in the quark triplet) until we
# break this symmetry with the Cartan H structure.

# The three Cartans of sl(4) that commute with T_BL are:
# H_01 = diag(1, -1, 0, 0), H_12 = diag(0, 1, -1, 0) — both commute with T_BL
# H_2 (traceless completion) completes the sl(3) subalgebra

# These Cartans generate the residual SU(3) → SU(2) × U(1) breaking
# IN THE QUARK SECTOR. In the NEUTRINO sector, they generate the
# three-generation hierarchy in the charged-lepton basis.

# The question: in the basis where the charged leptons are diagonal,
# what does the neutrino mass matrix look like?

# Natural Palatini ansatz:
# In "Palatini basis" (aligned with ad_T_BL eigenstructure):
#   m_nu^{Palatini} = diag(a, b, c)
# The charged-lepton mass matrix in the same basis:
#   m_l^{Palatini} = diag(m_e, m_mu, m_tau) (with some structure)

# PMNS = V_l† · V_nu where V_l, V_nu diagonalize m_l, m_nu

# If both are diagonal in the Palatini basis, PMNS = I (no mixing).
# But that's wrong observationally.

# The mixing comes from the DIFFERENT alignment of m_l's and m_nu's 
# eigenbasis relative to the Palatini basis.

# TM1 hypothesis:
# If the charged-lepton sector preserves the FIRST Palatini eigenvector
# (the one aligned with the "democratic" direction (1,1,1)/√3),
# then PMNS's first column inherits this, giving the TM1 structure.

# Let me test this

print("Numerical test: natural Palatini alignment → TM1?")
print("-" * 50)

# Work in the "Palatini basis" where T_BL is diagonal in SU(4)
# and the three generations align with the three +4/3 eigenspaces

# Charged-lepton mass matrix: if the bracket structure preserves 
# the "democratic" Palatini direction, m_l has a structure aligned
# with the (1,1,1)/√3 vector.

# Specifically, following Harrison-Perkins-Scott:
# If m_l^2 has an eigenvector (2, -1, -1)/√6 or (1, -1, 0)/√2 etc.,
# it matches TBM-column-1.
# If m_l^2 has eigenvector (2, -1, -1)/√6 specifically, it matches
# TM1 column 1.

# The question: does the Palatini bracket naturally produce m_l 
# diagonal in one of these bases?

# Build m_l from the Palatini structure:
# The charged-lepton Yukawa in sl(4) language is
#   Y_l = y_a · H_a + y_ij · A_{ij} + y_ij · S_{ij}
# where H_a are Cartans.

# At the Yukawa minimum, m_l = v · Y_l · (projection to lepton sector)
# This gives a 3×3 matrix in generation space.

# In sl(4) language with T_BL breaking to SU(3) × U(1)_BL:
# The three generations couple to the lepton direction (index 3)
# via the three pairs (0,3), (1,3), (2,3).

# Each such coupling is independently Palatini-allowed. So:
# Y_l^{diag(lepton)} = diag(y_03, y_13, y_23) × v_weak

# In generation basis where all three are equal (Palatini-symmetric):
# Y_l ∝ diag(y, y, y) = y · I — no mass hierarchy!

# But experimentally: m_e/m_mu ≈ 1/200, m_mu/m_tau ≈ 1/17.
# So the Palatini-symmetric ansatz is WRONG for charged leptons.

# The mass hierarchy requires BREAKING the residual SU(3) symmetry.
# This is done by the Cartan H_01 and H_12 generators.

# With BCH bracket structure up to order 3:
#   m_l = y_0 · 1 + y_1 · H_01 + y_2 · H_12 + cross-terms
# This is a general diagonal matrix in the (0,1,2) basis — no mixing!

# CONCLUSION: in the Palatini-aligned basis, m_l is diagonal.
# Similarly, m_nu (from Δ_R and bi-doublet Palatini couplings) is
# also naturally diagonal in THE SAME Palatini basis.

# If BOTH are diagonal in the same basis, PMNS = I, which is wrong.

# THE MIXING MUST COME FROM SOMEWHERE. Options:
#   (a) m_l and m_nu diagonal in DIFFERENT bases — misalignment gives PMNS
#   (b) Palatini bracket has off-diagonal generation-mixing we haven't used
#   (c) See-saw brings in M_R structure that breaks alignment

# Option (c) is most natural. Let's test it.

print("\nSee-saw structure:")
print(r"""
  m_ν^{eff} = m_D · M_R^{-1} · m_D^T
  
  If m_D is diagonal (a, b, c) and M_R is proportional to identity,
  m_ν is diagonal — no mixing.
  
  If M_R has structure from the Δ_R VEV breaking pattern:
    M_R = M_0 · P_palatini
  where P_palatini is a projection determined by the Δ_R VEV direction,
  then m_ν^eff has OFF-DIAGONAL structure in the m_D-diagonal basis.
""")

# The Delta_R VEV (10, 1, 3) has specific directional structure in SU(4)
# It couples to the FOURTH SU(4) index (lepton direction) with specific
# symmetric tensor structure.

# The 10 (symmetric traceless) representation of SU(4) in the 4×4 matrix
# form: 10-dim subspace of symmetric traceless matrices.
# Actually Delta_R is in (10, 1, 3): 10 of SU(4), 1 of SU(2)_L, 3 of SU(2)_R

# For the see-saw, the relevant coupling is Δ_R · ν_R^c · ν_R (where ν_R^c
# is the right-handed neutrino's charge-conjugate partner)

# The resulting M_R has the structure of a SYMMETRIC 3×3 matrix in
# generation space, with specific texture inherited from the Δ_R VEV.

# Natural Palatini ansatz for M_R:
# M_R = M_0 · (1 + ε_1 · H_01 + ε_2 · H_12 + cross-terms)
# This is the same structure as m_l! So M_R and m_l have the SAME 
# diagonalizing basis in the Palatini picture.

# If both are diagonal in the same basis, see-saw doesn't generate mixing.

# KEY INSIGHT: the PMNS mixing must come from something OUTSIDE the 
# Palatini bracket at order ≤ 3. Options:
#   (1) Higher-order effects (order 4+) — but Theorem C says these saturate
#   (2) RG running from PS scale to EW scale — known to be small
#   (3) Explicit breaking of the residual Palatini symmetry
#   (4) The 5 free parameters (tan β, ρ, α_1, α_2, β_c) provide the mixing

# Option (4) is the most honest: the Palatini bracket CONSTRAINS the 
# form of the mass matrices but does not FIX the specific mixing angles.
# Those are genuinely free parameters.

# This CONFIRMS the earlier finding from Phase 12 Task 1:
# the Palatini framework gives STRUCTURE (three generations, bracket
# form of mixing), not specific PMNS angles.

print("=" * 72)
print("TASK 1.3: DOES THE BRACKET FAVOR TM1, TBM, OR TM2?")
print("=" * 72)

print(r"""
TBM symmetry: S_4 (or equivalently A_4 in some formulations)
  Requires all three columns fixed by specific S_4 actions.

TM1 symmetry: residual Z_2 generated by the "democratic" vector (1,1,1)/√3
  This is the eigenvector of T_BL's trace-free partner in su(3).
  
TM2 symmetry: residual Z_2 generated by a different vector.

PALATINI'S NATURAL Z_2:
  The Palatini bracket commutes with T_BL and preserves its eigenvectors.
  T_BL has eigenvalue structure (+1/3, +1/3, +1/3, -1) in SU(4).
  The three equal +1/3 eigenvalues form a 3-dim eigenspace — 
  permutations of the three quark generations leave T_BL invariant.
  
  This S_3 permutation symmetry is the NATURAL Palatini residual.
  
  S_3 is larger than Z_2 but smaller than S_4.
  S_3 ⊂ S_4, and S_4 = S_3 × Z_2 (roughly).
  
  The Z_2 residual for TM1 corresponds to a specific S_3 generator
  (a 2-cycle).

CONCLUSION: 
  The Palatini bracket provides S_3 residual symmetry in the quark 
  triplet. This S_3 is CONSISTENT with TM1 (but doesn't uniquely 
  determine it — it's also consistent with TBM at a stricter level).
  
  To pick TM1 SPECIFICALLY, we would need to identify a symmetry-
  breaking pattern S_3 → Z_2 that aligns with TM1's residual.
  
  At our current understanding, the Palatini bracket UNDER-DETERMINES
  this choice. TM1, TM2, and TBM are all compatible with the bracket
  structure at the level of residual symmetry.

THIS IS AN HONEST FINDING, NOT A DERIVATION.
""")

print("=" * 72)
print("TASK 1.4: TM1 NUMERICAL PREDICTION vs DATA (REAFFIRMATION)")
print("=" * 72)

# Observed values (PDG 2024 + T2K/NOvA 2024)
theta_13_obs = 8.57; theta_13_err = 0.12
theta_12_obs = 33.41; theta_12_err = 0.75
theta_23_obs = 49.2; theta_23_err = 1.0

# TM1 predictions (derived from the ansatz with free θ)
# Given observed θ_13, predict θ_12 and θ_23
s13sq = np.sin(np.radians(theta_13_obs))**2

# TM1 formulas:
# sin²(θ_13) = (2/3) sin²(θ)        → solve for θ
# sin²(θ_12) = 1 / (3 cos²(θ_13))    (TM1 prediction)
# sin²(θ_23) = (1 - 2 sin²(θ_13)) / (2 - 2 sin²(θ_13)) (TM1 prediction)

s12sq_tm1 = 1 / (3 * (1 - s13sq))
s23sq_tm1 = (1 - 2*s13sq) / (2 - 2*s13sq)

theta_12_tm1 = np.degrees(np.arcsin(np.sqrt(s12sq_tm1)))
theta_23_tm1 = np.degrees(np.arcsin(np.sqrt(s23sq_tm1)))

# Pull
pull_12 = (theta_12_tm1 - theta_12_obs) / theta_12_err
pull_23 = (theta_23_tm1 - theta_23_obs) / theta_23_err

print(f"\nTM1 predictions (using measured θ_13 = {theta_13_obs}°):")
print(f"  {'Angle':>8s} {'Predicted':>12s} {'Observed':>12s} {'Pull':>8s}")
print(f"  {'θ_12':>8s} {theta_12_tm1:>10.2f}°  {theta_12_obs:>10.2f}°  {pull_12:>+6.1f}σ")
print(f"  {'θ_23':>8s} {theta_23_tm1:>10.2f}°  {theta_23_obs:>10.2f}°  {pull_23:>+6.1f}σ")

# TM2 for comparison
s12sq_tm2 = (1 - 3*s13sq) / (3 - 3*s13sq)  # 1/3 is fixed for TM2 col-2
# Actually TM2: sin²(θ_12) = (1 - 3·sin²(θ_13)) / (3 - 3·sin²(θ_13)) — let me verify
# TM2 has second column (1,1,1)/√3. Then (U)_e2 = 1/√3, giving sin²θ_12 cos²θ_13 = 1/3
s12sq_tm2 = (1/3) / (1 - s13sq)
theta_12_tm2 = np.degrees(np.arcsin(np.sqrt(s12sq_tm2)))
# TM2 θ_23: sin²θ_23 = 1/2 (maximal) with TM2 form
# Actually: (U)_mu2 = (U)_tau2 in TM2, so from unitarity with fixed column:
# These are related — the specific TM2 prediction is θ_23 = π/4 regardless of θ_13

theta_23_tm2 = 45.0

print(f"\nTM2 predictions (using measured θ_13 = {theta_13_obs}°):")
print(f"  {'θ_12':>8s} {theta_12_tm2:>10.2f}°  {theta_12_obs:>10.2f}°  {(theta_12_tm2-theta_12_obs)/theta_12_err:>+6.1f}σ")
print(f"  {'θ_23':>8s} {theta_23_tm2:>10.2f}°  {theta_23_obs:>10.2f}°  {(theta_23_tm2-theta_23_obs)/theta_23_err:>+6.1f}σ")

print(r"""
ASSESSMENT:
  TM1: θ_12 off by ~3σ, θ_23 off by ~5σ. Not a great fit.
  TM2: θ_12 off by more, θ_23 off by ~4σ. Worse.
  TBM: θ_13 = 0 (already excluded).

No pure ansatz fits all three angles well. Current global fits find
that data prefer NEITHER TM1 NOR TM2 exactly — the mixing matrix is
simply close to TBM with moderate corrections, and the corrections 
don't fall on any clean symmetry axis.

HONEST VERDICT:
  The Palatini framework's S_3 residual symmetry is COMPATIBLE with
  TM1 but does not PREDICT it. TM1 itself doesn't fit data perfectly.
  
  Therefore: the PMNS angles are genuinely fit parameters sitting in
  the 5 free Higgs couplings (α_1, α_2, β_c, tan β, ρ), not predictions
  of the Palatini bracket at any tractable order.
  
  This confirms the Phase 12 Task 1 finding and Phase 48 ledger:
    • θ_12, θ_13, θ_23 are FIT, not derived.
    • The Palatini framework gives STRUCTURE (three generations, 
      bracket-form mixing matrix), not NUMERICAL angle values.
    • Total input count stays at 7 (5 free + 2 calibrations).
""")

print("=" * 72)
print("TASK 1 — FINAL STATEMENT")
print("=" * 72)

print(r"""
RESULT: The Palatini bracket does NOT uniquely select TM1 over TBM
or TM2. All three are compatible with the S_3 residual symmetry
of the bracket in the quark-lepton triplet sector.

FURTHERMORE: TM1 itself fails to fit PMNS angles at the 3-5σ level.
The true data pattern is not captured by any single symmetric ansatz.

The ACS framework's PMNS prediction is therefore:
  "Three generations exist (Theorem C on ad_T_BL).
   Mass matrices have bracket-form structure with off-diagonal 
   couplings sitting in the 5 free Higgs parameters.
   Specific angle values are fit, not derived."

This is the cleanest honest statement. It removes θ_12, θ_13, θ_23 
from the "derived" ledger (already done in Phase 48) and replaces
the failed TBM-based derivation with a more accurate structural
statement.

NO NEW DERIVATION HAS BEEN OBTAINED. The task was genuine — we tested
whether TM1 was natural, and found it was not uniquely selected.
Reporting this honestly is the correct outcome.

The framework is neither strengthened nor weakened by this test.
The claim "Palatini predicts PMNS" was never correct at the
specific-angle level; this task confirms that it shouldn't be
made. The structural content (3 generations, bracket form, 
5 free parameters absorbing the mixing) survives.
""")
