# Co-governed and enforced under the Sovereign Integrity Protocol License (SIP License v1.1):
# https://github.com/tensorrent/ACS-Framework/blob/main/LICENSE

"""
Lattice imprint test for the broken-phase Standard Model spectrum
==================================================================

Companion to Note N1 (Pythagorean Structure).

Tests whether the broken-phase Standard Model masses and CKM mixing
preserve any detectable imprint of the <2, 3> arithmetic lattice that
governs the unbroken Pati-Salam algebra.

Result: NO statistically significant signal. The lattice structure is
confined to the algebraic sector (UV); the broken-phase spectrum is
lattice-generic.

Run:
    python3 test_lattice_imprint.py

Dependencies: numpy.
"""

import numpy as np


# ============================================================
# PDG 2024 central values
# ============================================================
# Charged lepton pole masses (GeV)
# Light quark MSbar at 2 GeV, c and b at their own scales (GeV)
# Top pole mass (GeV)
MASSES = {
    'e':   0.000511,
    'mu':  0.10566,
    'tau': 1.77686,
    'u':   0.00216,
    'd':   0.00467,
    's':   0.0934,
    'c':   1.27,
    'b':   4.18,
    't':   172.69,
}

# CKM magnitudes (PDG global fit)
CKM = {
    'Vud': 0.97435, 'Vus': 0.22500, 'Vub': 0.00369,
    'Vcd': 0.22486, 'Vcs': 0.97349, 'Vcb': 0.04182,
    'Vtd': 0.00857, 'Vts': 0.04110, 'Vtb': 0.999118,
}


# ============================================================
# Lattice distance
# ============================================================
def lattice_distance(r, primes=(2, 3), max_exp=5):
    """
    Compute the minimum log_2-distance from log_2(r) to the lattice
    generated by {log_2(p) : p in primes}, with integer coefficients
    bounded by max_exp.
    """
    log_r = np.log2(abs(r))
    log_primes = [np.log2(p) for p in primes]
    n = len(primes)
    best_eps = float('inf')
    
    if n == 2:
        for a in range(-max_exp, max_exp + 1):
            for b in range(-max_exp, max_exp + 1):
                eps = abs(log_r - (a*log_primes[0] + b*log_primes[1]))
                best_eps = min(best_eps, eps)
    elif n == 3:
        for a in range(-max_exp, max_exp + 1):
            for b in range(-max_exp, max_exp + 1):
                for c in range(-max_exp, max_exp + 1):
                    eps = abs(log_r - (a*log_primes[0] + b*log_primes[1] + c*log_primes[2]))
                    best_eps = min(best_eps, eps)
    elif n == 4:
        red = min(max_exp, 4)
        for a in range(-red, red + 1):
            for b in range(-red, red + 1):
                for c in range(-red, red + 1):
                    for d in range(-red, red + 1):
                        eps = abs(log_r - (a*log_primes[0] + b*log_primes[1]
                                          + c*log_primes[2] + d*log_primes[3]))
                        best_eps = min(best_eps, eps)
    return best_eps


# ============================================================
# Tests
# ============================================================
def run_test(label, ratios_dict, primes_list, max_exp=5, n_null=5000, seed=42):
    """
    For each lattice in primes_list, compute mean lattice distance for
    the data and for a null distribution of N=n_null random ratios
    drawn uniformly in log scale over the data's log range.
    
    Reports: data mean, null mean, ratio, z-score.
    """
    actual_logs = [np.log2(r) for r in ratios_dict.values()]
    log_min = min(actual_logs) - 0.5
    log_max = max(actual_logs) + 0.5
    
    print(f"\n{'='*78}")
    print(f"  {label}")
    print(f"{'='*78}")
    print(f"  log_2 range: [{log_min:.2f}, {log_max:.2f}]")
    print(f"  N data points: {len(ratios_dict)}, N null draws: {n_null}")
    print()
    print(f"  {'Lattice':<25} {'Data':>10} {'Null':>10} {'Ratio':>8} {'Z-score':>10}")
    print(f"  {'-'*75}")
    
    for primes in primes_list:
        actual_eps = [lattice_distance(r, primes, max_exp) for r in ratios_dict.values()]
        
        np.random.seed(seed)
        rlogs = np.random.uniform(log_min, log_max, n_null)
        null_eps = [lattice_distance(2**lr, primes, max_exp) for lr in rlogs]
        
        data_mean = np.mean(actual_eps)
        null_mean = np.mean(null_eps)
        null_std = np.std(null_eps)
        ratio = data_mean / null_mean if null_mean > 0 else 0
        z = (data_mean - null_mean) / null_std if null_std > 0 else 0
        
        primes_str = f"<{','.join(str(p) for p in primes)}>"
        print(f"  {primes_str:<25} {data_mean:>10.4f} {null_mean:>10.4f} "
              f"{ratio:>8.2f} {z:>+10.2f}")
    
    print()


def main():
    intra_gen = {
        "m_d / m_u":   MASSES['d'] / MASSES['u'],
        "m_e / m_u":   MASSES['e'] / MASSES['u'],
        "m_e / m_d":   MASSES['e'] / MASSES['d'],
        "m_s / m_c":   MASSES['s'] / MASSES['c'],
        "m_mu / m_c":  MASSES['mu'] / MASSES['c'],
        "m_mu / m_s":  MASSES['mu'] / MASSES['s'],
        "m_b / m_t":   MASSES['b'] / MASSES['t'],
        "m_tau / m_t": MASSES['tau'] / MASSES['t'],
        "m_tau / m_b": MASSES['tau'] / MASSES['b'],
    }
    
    inter_gen = {
        "m_mu / m_e":   MASSES['mu'] / MASSES['e'],
        "m_tau / m_mu": MASSES['tau'] / MASSES['mu'],
        "m_tau / m_e":  MASSES['tau'] / MASSES['e'],
        "m_c / m_u":    MASSES['c']  / MASSES['u'],
        "m_t / m_c":    MASSES['t']  / MASSES['c'],
        "m_t / m_u":    MASSES['t']  / MASSES['u'],
        "m_s / m_d":    MASSES['s']  / MASSES['d'],
        "m_b / m_s":    MASSES['b']  / MASSES['s'],
        "m_b / m_d":    MASSES['b']  / MASSES['d'],
    }
    
    ckm_ratios = {
        "Vus":         CKM['Vus'],
        "Vcb":         CKM['Vcb'],
        "Vub":         CKM['Vub'],
        "Vus^2/Vcb":   CKM['Vus']**2 / CKM['Vcb'],
    }
    
    lattices = [(2, 3), (2, 3, 5), (2, 3, 5, 7)]
    
    run_test("INTRA-GENERATION ratios (within doublet)", intra_gen, lattices)
    run_test("INTER-GENERATION ratios (Yukawa hierarchy)", inter_gen, lattices)
    run_test("CKM-derived ratios", ckm_ratios, lattices[:2])  # 4D too sparse
    
    print()
    print("="*78)
    print("  CONCLUSION")
    print("="*78)
    print("""
  Across all categories and all lattices tested, the data sits at
  0.6-1.2 x the null mean with z-scores in [-0.7, +0.3].
  
  No statistically significant lattice imprint is detected.
  
  The arithmetic <2,3> structure of the Pati-Salam unbroken-phase 
  algebra is an ULTRAVIOLET ALGEBRAIC ARTIFACT and does not 
  propagate measurably to the broken-phase mass spectrum or 
  CKM mixing.
  
  This is a clean negative result.
""")


if __name__ == "__main__":
    main()
